config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  post  "login"           => "users#login"
  get   "reset_password"  => "users#reset_password"

  resources :users do
    member do
    end

    collection do
    end

    resources :board_definitions do
      resources :cell_options
    end

    resources :game_boards do

    end
  end

  resources :games do
  end

  root 'welcome#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  validates_presence_of :screen_name, :email
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    # TODO - restrict _authorization_ to admin-only
    @users = User.all
  end

  def show
    find_user
  end

  def new
  end

  def edit
  end

  def create
    @user = User.create!(user_params)
    redirect_to @user
  end

  def update
    find_user
    if @user.update(user_params)
      redirect_to @user
    else
      render "edit"
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to "/" # TODO - maybe add a "thank you page or something?"
  end

  def reset_password
    @user = User.find(params[:id])
    # TODO - for now, email a new random password, expiring after X minutes
    # TODO - maybe setup a lockout table or column... probably table
  end

  def login
    @user = User.find_by_email(params[:email])
    if @user.present?
      # TODO - add password/authentication logic
    end
    raise "User email/password combination not found" if @user.nil?
    redirect_to @user
  end


  private
    def find_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:email, :screen_name)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bingo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <%= yield %>
  </div>

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</body>
</html>

app/views/users/index.html.erb
<p><strong><%= link_to("Home", controller: "welcome") %></strong></p>
<h1>Bingo Users</h1>
<% text = (@users.size == 1) ? "1 User currently exists" : "#{@users.size} Users currently exist" %>
<p><strong><%= text %> in the system.</strong></p>
<% if @users.present? %>
  <!-- TABLES ARE EVIL  ...  USE CSS, DUMMY!! -->
  <table border="1" cellspacing="0" cellpadding="7">
    <tr>
      <th align="left">ID</th>
      <th align="left">Email</th>
      <th align="left">Screen Name</th>
    </tr>
    <% @users.each do |user| %>
      <tr>
        <td align="left"><%= user.id %></td>
        <td align="left"><%= user.email %></td>
        <td align="left"><%= user.screen_name %></td>
      </tr>
    <% end %>
  </table>
<% end %>

app/views/users/login.html.erb
<h1>Users#login</h1>
<p>Find me in app/views/users/login.html.erb</p>

app/views/users/show.html.erb
<p><strong><%= link_to("Home", controller: "welcome") %></strong></p>
<h1>Bingo User - <%= @user.screen_name %></h1>
<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

app/views/welcome/index.html.erb
<h1>Welcome to Bingo!</h1>

<p><strong><%= link_to("View All Users", controller: "users") %></strong></p>

<div class="auth login">
  <h3>Login</h3>
  <%= form_tag(login_path, method: "post") do %>
    <fieldset class="form-group">
      <%= label_tag(:email, "Email:", for: 'email') %>
      <%= email_field_tag :email, '', class: 'form-control', required: 'required' %>
    </fieldset>
    <fieldset class="form-group">
      <%= button_tag("Login!", class: 'btn btn-primary', role: 'button')  %>
    </fieldset>
  <% end %>
</div>

<div class="auth register">
  <h3>Register</h3>
  <%= form_for(:user, url: users_path) do |f| %>
    <fieldset class="form-group">
      <%= label_tag(:email, "Email:", for: 'user_email') %>
      <%= f.email_field :email, class: 'form-control', required: 'required' %>
    </fieldset>
    <fieldset class="form-group">
      <%= label_tag(:screen_name, "Screen Name:", for: 'user_screen_name') %>
      <%= f.text_field :screen_name, class: 'form-control', required: 'required' %>
    </fieldset>
    <fieldset class="form-group">
      <%= f.button "Create!", class: 'btn btn-primary', role: 'button' %>
    </fieldset>
  <% end %>
</div>